name: IntegrationTests
trigger:
  batch: false
  branches:
    include:
    - master

jobs:
- job: IntegrationTests
  pool:
    vmImage: "Ubuntu-16.04"
  steps:
  - task: UsePythonVersion@0
    displayName: Use python 3.7
    inputs:
      versionSpec: "3.7"
  - script: pip install tox
    displayName: Install tox
  - script: tox -e integration
    displayName: Run integration tests
    env:
      DD_TEST_CLIENT_API_KEY: $(datadogAPIKey)
      DD_TEST_CLIENT_APP_KEY: $(datadogAPPKey)
      DD_TEST_CLIENT_USER: $(datadogTestUser)
  - script: tox -e integration-admin
    displayName: Run admin integration tests
    env:
      DD_TEST_CLIENT_API_KEY: $(datadogAPIKey)
      DD_TEST_CLIENT_APP_KEY: $(datadogAPPKey)
      DD_TEST_CLIENT_USER: $(datadogTestUser)
