name: "Ensure labels"
on: # yamllint disable-line rule:truthy
  pull_request:
    types:
      - labeled
      - unlabeled
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Check changelog labels
        if: github.event.pull_request.draft == false && false == contains(join(github.event.pull_request.labels.*.name, ','), 'changelog/')
        run: |-
          echo "::error Add 'changelog/*' label";
          exit 1;
      - name: OK
        run: echo "Thank you!"
