name: "Pull Request Labeler"

permissions:
  contents: read
  pull-requests: write

on:
- pull_request

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: DataDog/labeler@5170395583c7f7ec92989fd24faffc5b6154b866 # glob-all
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
