name: Build

permissions:
  contents: write
  pull-requests: write

on:
  pull_request:
  release:
    types:
      - published

jobs:
  build_wheels:
    name: Build wheels on Ubuntu latest
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    environment: secure_publish_environment
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        # Include all history and tags, needed for building the right version
        with:
          fetch-depth: 0

      - name: Build distributions
        run: |
          python3 -m venv .venv
          .venv/bin/pip install build
          .venv/bin/python -m build

      # Publish wheels to PyPI using Trusted Publishers.
      # https://docs.pypi.org/trusted-publishers/using-a-publisher/
      # This job needs to run from within the pypi-datadog-checks-base environment. PyPi
      # validates the workflow file name, environment and repository the request is
      # comming from to provide the valid JWT token.
      - name: Release base package to PyPI
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # v1.14.0
        with:
          skip-existing: true
